apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-configmap
  namespace: default
data:
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
  POSTGRES_SERVER: "=postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "app_todo_dev"